"""initial relational schema

Revision ID: 0001_initial
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("students", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("full_name", sa.String(255)), sa.Column("university", sa.String(255)), sa.Column("degree", sa.String(255)), sa.Column("graduation_year", sa.Integer()), sa.Column("cgpa", sa.Numeric(4, 2)), sa.Column("resume_text", sa.Text()), sa.Column("career_goals", postgresql.JSONB(), nullable=False), sa.Column("preferred_locations", postgresql.JSONB(), nullable=False))
    op.create_table("companies", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("company_name", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("industry", sa.String(255)), sa.Column("website", sa.String(500)), sa.Column("location", sa.String(255)))
    op.create_table("internships", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("company_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("domain", sa.String(255)), sa.Column("location", sa.String(255)), sa.Column("duration", sa.String(100)), sa.Column("seats", sa.Integer(), nullable=False), sa.Column("minimum_cgpa", sa.Numeric(4, 2)), sa.Column("minimum_graduation_year", sa.Integer()), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("preferences", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("student_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("ranked_internship_ids", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)))
    op.create_table("applications", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("student_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("students.id", ondelete="CASCADE"), nullable=False), sa.Column("internship_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("internships.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("student_id", "internship_id", name="uq_application_student_internship"))
    op.create_table("allocation_runs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("run_number", sa.String(50), nullable=False, unique=True), sa.Column("status", sa.String(30), nullable=False), sa.Column("weights_snapshot", postgresql.JSONB(), nullable=False), sa.Column("student_count", sa.Integer(), nullable=False), sa.Column("internship_count", sa.Integer(), nullable=False), sa.Column("allocated_count", sa.Integer(), nullable=False), sa.Column("unallocated_count", sa.Integer(), nullable=False), sa.Column("average_match_score", sa.Numeric(7, 3)), sa.Column("preference_satisfaction", sa.Numeric(7, 3)), sa.Column("fairness_score", sa.Numeric(7, 3)), sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)))
    op.create_table("allocations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("allocation_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("student_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("students.id"), nullable=False), sa.Column("internship_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("internships.id"), nullable=False), sa.Column("match_score", sa.Numeric(7, 3), nullable=False), sa.Column("score_breakdown", postgresql.JSONB(), nullable=False), sa.Column("allocation_reason", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("run_id", "student_id", name="uq_allocation_run_student"))
    op.create_table("weight_configs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("skill_weight", sa.Numeric(6, 2), nullable=False), sa.Column("location_weight", sa.Numeric(6, 2), nullable=False), sa.Column("career_weight", sa.Numeric(6, 2), nullable=False), sa.Column("preference_weight", sa.Numeric(6, 2), nullable=False), sa.Column("company_weight", sa.Numeric(6, 2), nullable=False), sa.Column("fairness_weight", sa.Numeric(6, 2), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True)))


def downgrade():
    for table in ("allocations", "allocation_runs", "weight_configs", "applications", "preferences", "internships", "companies", "students", "users"):
        op.drop_table(table)
